#Example: "C:\\Users\\YourUsername\\Desktop"
#Defaults to the Windows desktop directory if left blank
desktopPath:

#The application will create a subfolder named after the current date
#Defaults to the set desktop directory if left blank
destinationPath:

#Add the full names of the files you don't want the app to touch.
blacklistedFiles:
  - desktop.ini #Do not delete

#Example: .exe
blacklistedExtensions:
  -